version : '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx.dockerfile
      args:
        - SITENAME=ambientsense
        - PORT=8080
    container_name: ambientsense_nginx
    volumes:
      - /var/src/samplesite/www:/var/www/ambientsense
      - /var/www/node_modules:/var/www/libs
    ports:
      - "8080:8080"
